In [1]:
import os

os.chdir("..")

In [2]:
from src.data_process import DataCal
import polars as pl

dc = DataCal()

In [10]:
df = dc.gen_nuti_data()
df.group_by(["year"]).agg(pl.col("total_calories").sum()).sort(["year"])

shape: (24, 2)
┌──────┬────────────────┐
│ year ┆ total_calories │
│ ---  ┆ ---            │
│ i32  ┆ f64            │
╞══════╪════════════════╡
│ 2002 ┆ 3.4307e11      │
│ 2003 ┆ 6.2304e11      │
│ 2004 ┆ 6.4502e11      │
│ 2005 ┆ 6.5780e11      │
│ 2006 ┆ 6.8050e11      │
│ …    ┆ …              │
│ 2021 ┆ 6.6998e11      │
│ 2022 ┆ 6.4917e11      │
│ 2023 ┆ 5.9900e11      │
│ 2024 ┆ 6.1929e11      │
│ 2025 ┆ 1.5814e11      │
└──────┴────────────────┘

In [ ]:
df.write_csv("3-9-2025-calories.csv")

In [6]:
nutri_df = pl.read_parquet(f"{dc.saving_dir}external/nutri_matrix.parquet")
df = dc.process_int_org(time_frame="monthly", level="hts")
nutri_df = nutri_df.rename({"schedule_b": "hts_code"}).drop("description")
df = df.with_columns(hts_code=pl.col("hts_code").str.slice(0, 4))
master = df.join(nutri_df, on="hts_code", how="inner")

In [7]:
master

shape: (252_261, 33)
┌──────┬───────┬──────────┬─────────┬───┬──────────────┬────────────┬─────────┬──────────────┐
│ year ┆ month ┆ hts_code ┆ imports ┆ … ┆ vitamin_d_iu ┆ calcium_mg ┆ iron_mg ┆ potassium_mg │
│ ---  ┆ ---   ┆ ---      ┆ ---     ┆   ┆ ---          ┆ ---        ┆ ---     ┆ ---          │
│ i32  ┆ i8    ┆ str      ┆ i64     ┆   ┆ f64          ┆ f64        ┆ f64     ┆ f64          │
╞══════╪═══════╪══════════╪═════════╪═══╪══════════════╪════════════╪═════════╪══════════════╡
│ 2002 ┆ 7     ┆ 0201     ┆ 490253  ┆ … ┆ 0.0          ┆ 7.0        ┆ 1.96    ┆ 273.0        │
│ 2002 ┆ 7     ┆ 0201     ┆ 933406  ┆ … ┆ 0.0          ┆ 7.0        ┆ 1.96    ┆ 273.0        │
│ 2002 ┆ 7     ┆ 0201     ┆ 1391780 ┆ … ┆ 0.0          ┆ 7.0        ┆ 1.96    ┆ 273.0        │
│ 2002 ┆ 7     ┆ 0201     ┆ 1742546 ┆ … ┆ 0.0          ┆ 7.0        ┆ 1.96    ┆ 273.0        │
│ 2002 ┆ 7     ┆ 0201     ┆ 3768955 ┆ … ┆ 0.0          ┆ 7.0        ┆ 1.96    ┆ 273.0        │
│ …    ┆ …     ┆ …        ┆ …       ┆ … ┆ …            ┆ …          ┆ …       ┆ …            │
│ 2025 ┆ 3     ┆ 2208     ┆ 99831   ┆ … ┆ 0.0          ┆ 8.0        ┆ 0.0     ┆ 92.0         │
│ 2025 ┆ 3     ┆ 2208     ┆ 34176   ┆ … ┆ 0.0          ┆ 8.0        ┆ 0.0     ┆ 92.0         │
│ 2025 ┆ 3     ┆ 2209     ┆ 33423   ┆ … ┆ 0.0          ┆ 6.0        ┆ 0.0     ┆ 2.0          │
│ 2025 ┆ 3     ┆ 2209     ┆ 6361    ┆ … ┆ 0.0          ┆ 6.0        ┆ 0.0     ┆ 2.0          │
│ 2025 ┆ 3     ┆ 2209     ┆ 214556  ┆ … ┆ 0.0          ┆ 6.0        ┆ 0.0     ┆ 2.0          │
└──────┴───────┴──────────┴─────────┴───┴──────────────┴────────────┴─────────┴──────────────┘

In [ ]:
nutri_df